/* Generated By:JJTree: Do not edit this line. ASTDictionaryPair.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.nokok.karaffe.parser;

public
class ASTDictionaryPair extends SimpleNode {
  public ASTDictionaryPair(int id) {
    super(id);
  }

  public ASTDictionaryPair(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws net.nokok.karaffe.parser.excptn.ParserException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=135b78fb4dfb12e1a9459afa80f2dc7f (do not edit this line) */
