/* Generated By:JJTree: Do not edit this line. ASTDecimalFPLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.nokok.karaffe.parser;

public class ASTDecimalFPLiteral extends SimpleNode {

    public ASTDecimalFPLiteral(int id) {
        super(id);
    }

    public ASTDecimalFPLiteral(Parser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(ParserVisitor visitor, Object data) throws net.nokok.karaffe.parser.excptn.ParserException {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=823d385b7a29fa3f95bc958b58404546 (do not edit this line) */
