/* Generated By:JJTree: Do not edit this line. ASTFuncLiteralArg.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.nokok.karaffe.parser;

public class ASTFuncLiteralArg extends SimpleNode {

    public ASTFuncLiteralArg(int id) {
        super(id);
    }

    public ASTFuncLiteralArg(Parser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(ParserVisitor visitor, Object data) throws net.nokok.karaffe.parser.excptn.ParserException {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=a74dc6781f6a2d4a98682062e839980b (do not edit this line) */
