/* Generated By:JJTree: Do not edit this line. ASTLessThanEqTo.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.nokok.karaffe.parser;

public class ASTLessThanEqTo extends SimpleNode {

    public ASTLessThanEqTo(int id) {
        super(id);
    }

    public ASTLessThanEqTo(Parser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(ParserVisitor visitor, Object data) throws net.nokok.karaffe.parser.excptn.ParserException {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=049ef71f17209fdf54513000cc8546f1 (do not edit this line) */
