/* Generated By:JJTree: Do not edit this line. ASTSuperTypeAndInterfaces.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.nokok.karaffe.parser;

public
class ASTSuperTypeAndInterfaces extends SimpleNode {
  public ASTSuperTypeAndInterfaces(int id) {
    super(id);
  }

  public ASTSuperTypeAndInterfaces(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws net.nokok.karaffe.parser.excptn.ParserException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8b1a7cd1ab103a89f25900f04a46ec6c (do not edit this line) */
