/* Generated By:JavaCC: Do not edit this line. KaraffeParserTreeConstants.java Version 6.0_1 */
package net.nokok.karaffe.parser;

public interface KaraffeParserTreeConstants {

    public int JJTCOMPILEUNIT = 0;
    public int JJTSTATEMENT = 1;
    public int JJTDECLARATION = 2;
    public int JJTTYPEDCL = 3;
    public int JJTINTERFACEDCL = 4;
    public int JJTVARIABLEDCL = 5;
    public int JJTVARIABLETYPEDCL = 6;
    public int JJTTYPEPARAMETERS = 7;
    public int JJTEXPRESSION = 8;
    public int JJTLITERAL = 9;
    public int JJTFUNCTIONLITERAL = 10;
    public int JJTFUNCTIONVARIABLEBINDING = 11;
    public int JJTIDENTIFIER = 12;
    public int JJTEQUALOPERATOR = 13;
    public int JJTLESSTHANOPERATOR = 14;
    public int JJTGREATERTHANOPERATOR = 15;
    public int JJTPLUS = 16;
    public int JJTMINUS = 17;
    public int JJTSTAROPERATOR = 18;
    public int JJTSLASHOPERATOR = 19;
    public int JJTPERCENTOPERATOR = 20;
    public int JJTTILDEOPERATOR = 21;
    public int JJTBANGOPERATOR = 22;
    public int JJTANDOPERATOR = 23;
    public int JJTOROPERATOR = 24;
    public int JJTHATOPERATOR = 25;
    public int JJTQUESTIONOPERATOR = 26;
    public int JJTARROWOPERATOR = 27;
    public int JJTNEWLINE = 28;

    public String[] jjtNodeName = {
        "CompileUnit",
        "Statement",
        "Declaration",
        "TypeDcl",
        "InterfaceDcl",
        "VariableDcl",
        "VariableTypeDcl",
        "TypeParameters",
        "Expression",
        "Literal",
        "FunctionLiteral",
        "FunctionVariableBinding",
        "Identifier",
        "EqualOperator",
        "LessThanOperator",
        "GreaterThanOperator",
        "Plus",
        "Minus",
        "StarOperator",
        "SlashOperator",
        "PercentOperator",
        "TildeOperator",
        "BangOperator",
        "AndOperator",
        "OrOperator",
        "HatOperator",
        "QuestionOperator",
        "ArrowOperator",
        "NewLine",};
}
/* JavaCC - OriginalChecksum=8c37fdd007a17923179faf7178a1aa76 (do not edit this line) */
