/* Generated By:JavaCC: Do not edit this line. KaraffeParserVisitor.java Version 6.0_1 */
package net.nokok.karaffe.parser;

public interface KaraffeParserVisitor {

    public Object visit(SimpleNode node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTCompileUnit node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTStatement node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTDeclaration node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTTypeDcl node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTInterfaceDcl node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTVariableDcl node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTVariableTypeDcl node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTTypeParameters node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTExpression node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTLiteral node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTFunctionLiteral node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTFunctionVariableBinding node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTIdentifier node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTEqualOperator node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTLessThanOperator node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTGreaterThanOperator node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTPlus node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTMinus node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTArrowOperator node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;

    public Object visit(ASTNewLine node, Object data) throws net.nokok.karaffe.parser.excptn.KaraffeParserException;
}
/* JavaCC - OriginalChecksum=75e082214c6d14dad1451a0e0ff41fc6 (do not edit this line) */
