/* Generated By:JJTree&JavaCC: Do not edit this line. KaraffeParserConstants.java */
package net.nokok.karaffe.parser;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KaraffeParserConstants {

    /** End of File. */
    int EOF = 0;
    /** RegularExpression Id. */
    int EndOfLine = 7;
    /** RegularExpression Id. */
    int Abstract = 9;
    /** RegularExpression Id. */
    int Check = 10;
    /** RegularExpression Id. */
    int Enum = 11;
    /** RegularExpression Id. */
    int Import = 12;
    /** RegularExpression Id. */
    int Interface = 13;
    /** RegularExpression Id. */
    int Lazy = 14;
    /** RegularExpression Id. */
    int Module = 15;
    /** RegularExpression Id. */
    int Operator = 16;
    /** RegularExpression Id. */
    int Override = 17;
    /** RegularExpression Id. */
    int Private = 18;
    /** RegularExpression Id. */
    int Sealed = 19;
    /** RegularExpression Id. */
    int Switch = 20;
    /** RegularExpression Id. */
    int Type = 21;
    /** RegularExpression Id. */
    int UnaryOperator = 22;
    /** RegularExpression Id. */
    int TypeAlias = 23;
    /** RegularExpression Id. */
    int Undefined = 24;
    /** RegularExpression Id. */
    int Variable = 25;
    /** RegularExpression Id. */
    int BoolLiteral = 26;
    /** RegularExpression Id. */
    int IntLiteral = 27;
    /** RegularExpression Id. */
    int Hexadecimal = 28;
    /** RegularExpression Id. */
    int HexDigit = 29;
    /** RegularExpression Id. */
    int FloatLiteral = 30;
    /** RegularExpression Id. */
    int Zero = 31;
    /** RegularExpression Id. */
    int NonZero = 32;
    /** RegularExpression Id. */
    int Exp = 33;
    /** RegularExpression Id. */
    int StringLiteral = 34;
    /** RegularExpression Id. */
    int StringCharacter = 35;
    /** RegularExpression Id. */
    int StringEscapeSeq = 36;
    /** RegularExpression Id. */
    int UnicodeEscape = 37;
    /** RegularExpression Id. */
    int Identifier = 38;
    /** RegularExpression Id. */
    int IdentifierHead = 39;
    /** RegularExpression Id. */
    int IdentifierChar = 40;
    /** RegularExpression Id. */
    int JavaFQCN = 41;
    /** RegularExpression Id. */
    int LeftBracket = 42;
    /** RegularExpression Id. */
    int RightBracket = 43;
    /** RegularExpression Id. */
    int LeftBrace = 44;
    /** RegularExpression Id. */
    int RightBrace = 45;
    /** RegularExpression Id. */
    int LeftParen = 46;
    /** RegularExpression Id. */
    int RightParen = 47;
    /** RegularExpression Id. */
    int Colon = 48;
    /** RegularExpression Id. */
    int DoubleColon = 49;
    /** RegularExpression Id. */
    int Dot = 50;
    /** RegularExpression Id. */
    int EqualSign = 51;
    /** RegularExpression Id. */
    int AA = 52;
    /** RegularExpression Id. */
    int SA = 53;
    /** RegularExpression Id. */
    int MA = 54;
    /** RegularExpression Id. */
    int DA = 55;
    /** RegularExpression Id. */
    int RA = 56;
    /** RegularExpression Id. */
    int Lt = 57;
    /** RegularExpression Id. */
    int LtE = 58;
    /** RegularExpression Id. */
    int Gt = 59;
    /** RegularExpression Id. */
    int GtE = 60;
    /** RegularExpression Id. */
    int Plus = 61;
    /** RegularExpression Id. */
    int Minus = 62;
    /** RegularExpression Id. */
    int Star = 63;
    /** RegularExpression Id. */
    int Slash = 64;
    /** RegularExpression Id. */
    int SafeDiv = 65;
    /** RegularExpression Id. */
    int Percent = 66;
    /** RegularExpression Id. */
    int SafeRem = 67;
    /** RegularExpression Id. */
    int Tilde = 68;
    /** RegularExpression Id. */
    int Bang = 69;
    /** RegularExpression Id. */
    int And = 70;
    /** RegularExpression Id. */
    int Or = 71;
    /** RegularExpression Id. */
    int Hat = 72;
    /** RegularExpression Id. */
    int Question = 73;
    /** RegularExpression Id. */
    int ReverseArrow = 74;
    /** RegularExpression Id. */
    int ReverseArrowChar = 75;
    /** RegularExpression Id. */
    int SingleArrowChar = 76;
    /** RegularExpression Id. */
    int SingleArrow = 77;
    /** RegularExpression Id. */
    int CastArrow = 78;
    /** RegularExpression Id. */
    int TypeCheckArrow = 79;
    /** RegularExpression Id. */
    int DoubleArrow = 80;
    /** RegularExpression Id. */
    int EqualTo = 81;
    /** RegularExpression Id. */
    int NotEqualTo = 82;
    /** RegularExpression Id. */
    int NonComparable = 83;
    /** RegularExpression Id. */
    int Comparable = 84;
    /** RegularExpression Id. */
    int ClosedRange = 85;
    /** RegularExpression Id. */
    int HalfOpenRange = 86;
    /** RegularExpression Id. */
    int NewLine = 87;
    /** RegularExpression Id. */
    int Atmark = 88;

    /** Lexical state. */
    int DEFAULT = 0;
    /** Lexical state. */
    int InComment = 1;

    /** Literal token values. */
    String[] tokenImage = {
        "<EOF>",
        "\" \"",
        "\"\\t\"",
        "<token of kind 3>",
        "\"/*\"",
        "\"/*\"",
        "<token of kind 6>",
        "<EndOfLine>",
        "\"*/\"",
        "\"abstract\"",
        "\"check\"",
        "\"enum\"",
        "\"import\"",
        "\"interface\"",
        "\"lazy\"",
        "\"module\"",
        "\"op\"",
        "\"override\"",
        "\"private\"",
        "\"sealed\"",
        "\"switch\"",
        "\"type\"",
        "\"unaryop\"",
        "\"typealias\"",
        "\"undefined\"",
        "\"var\"",
        "<BoolLiteral>",
        "<IntLiteral>",
        "<Hexadecimal>",
        "<HexDigit>",
        "<FloatLiteral>",
        "\"0\"",
        "<NonZero>",
        "<Exp>",
        "<StringLiteral>",
        "<StringCharacter>",
        "<StringEscapeSeq>",
        "<UnicodeEscape>",
        "<Identifier>",
        "<IdentifierHead>",
        "<IdentifierChar>",
        "<JavaFQCN>",
        "\"[\"",
        "\"]\"",
        "\"{\"",
        "\"}\"",
        "\"(\"",
        "\")\"",
        "\":\"",
        "\"::\"",
        "\".\"",
        "\"=\"",
        "\"+=\"",
        "\"-=\"",
        "\"*=\"",
        "\"/=\"",
        "\"%=\"",
        "\"<\"",
        "\"<=\"",
        "\">\"",
        "\">=\"",
        "\"+\"",
        "\"-\"",
        "\"*\"",
        "\"/\"",
        "\"/?\"",
        "\"%\"",
        "\"%?\"",
        "\"~\"",
        "\"!\"",
        "\"&\"",
        "\"|\"",
        "\"^\"",
        "\"?\"",
        "\"<-\"",
        "\"\\u2190\"",
        "\"\\u2192\"",
        "\"->\"",
        "\"~>\"",
        "\"~>?\"",
        "\"=>\"",
        "\"==\"",
        "\"!=\"",
        "\"!<>=\"",
        "\"<>=\"",
        "\"..\"",
        "\".<\"",
        "<NewLine>",
        "\"@\"",
        "\"#\"",};

}
