/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package net.nokok.karaffe.parser;

public interface ParserTreeConstants {

    public int JJTCOMPILEUNIT = 0;
    public int JJTPACKAGEDECL = 1;
    public int JJTMODULENAME = 2;
    public int JJTIMPORTSTMT = 3;
    public int JJTSIMPLEIMPORT = 4;
    public int JJTALIASIMPORT = 5;
    public int JJTIMPORTAFTER = 6;
    public int JJTTYPENAME = 7;
    public int JJTTYPEDECL = 8;
    public int JJTCLASSDECL = 9;
    public int JJTCLASSMODIFIER = 10;
    public int JJTTYPEPARAMETERS = 11;
    public int JJTTYPEPARAMETER = 12;
    public int JJTTYPEBOUND = 13;
    public int JJTCLASSORINTERFACETYPE = 14;
    public int JJTCLASSTYPE = 15;
    public int JJTADDITIONALBOUND = 16;
    public int JJTSUPERTYPE = 17;
    public int JJTINTERFACES = 18;
    public int JJTINTERFACETYPE = 19;
    public int JJTCLASSBODY = 20;
    public int JJTCLASSBODYDECL = 21;
    public int JJTCLASSCTORDECL = 22;
    public int JJTCTORMODIFIER = 23;
    public int JJTFORMALPARAMETERS = 24;
    public int JJTFORMALPARAMETER = 25;
    public int JJTLASTFORMALPARAMTER = 26;
    public int JJTVARIABLEMODIFIER = 27;
    public int JJTCTORBODY = 28;
    public int JJTEXPLICITCTORINVOCATION = 29;
    public int JJTBLOCKSTMTS = 30;
    public int JJTBLOCKSTMT = 31;
    public int JJTLOCALVALDECL = 32;
    public int JJTVARIABLEINITIALIZER = 33;
    public int JJTVARIABLETYPE = 34;
    public int JJTFIELDDECL = 35;
    public int JJTFIELDMODIFIER = 36;
    public int JJTFIELDINITIALIZER = 37;
    public int JJTFUNCDECL = 38;
    public int JJTFUNCMODIFIER = 39;
    public int JJTRETURNTYPE = 40;
    public int JJTFUNCBODY = 41;
    public int JJTALGEBRAICDATATYPEDECL = 42;
    public int JJTALGEBRAICDATATYPEBODY = 43;
    public int JJTALGEBRAICDATACTORBINDING = 44;
    public int JJTINTERFACEDECL = 45;
    public int JJTINTERFACEMODIFIER = 46;
    public int JJTEXTENDSINTERFACES = 47;
    public int JJTINTERFACEBODY = 48;
    public int JJTINTERFACEMEMBER = 49;
    public int JJTCONSTANTDECL = 50;
    public int JJTCONSTANTMODIFIER = 51;
    public int JJTINTERFACEMETHODDECL = 52;
    public int JJTTYPEALIASDECL = 53;
    public int JJTTYPEALIASMODIFIER = 54;
    public int JJTENUMDECL = 55;
    public int JJTENUMMODIFIER = 56;
    public int JJTENUMNAME = 57;
    public int JJTENUMMEMBERS = 58;
    public int JJTIDENTIFIER = 59;
    public int JJTEXPRESSION = 60;
    public int JJTASSIGNMENTEXPR = 61;
    public int JJTASSIGNMENTOP = 62;
    public int JJTLEFTHANDSIDE = 63;
    public int JJTBOOLOREXPR = 64;
    public int JJTBOOLANDEXPR = 65;
    public int JJTEQUALITYEXPR = 66;
    public int JJTRELATIONALEXPR = 67;
    public int JJTRANGEEXPR = 68;
    public int JJTADDITIVEEXPR = 69;
    public int JJTMULTIPLICATIVEEXPR = 70;
    public int JJTUNARYEXPR = 71;
    public int JJTUNARYEXPRNOTPLUSMINUS = 72;
    public int JJTCASTEXPR = 73;
    public int JJTCHECKEXPR = 74;
    public int JJTPOSTFIXEXPR = 75;
    public int JJTPRIMARY = 76;
    public int JJTLISTDISPLAY = 77;
    public int JJTDICTIONARYDISPLAY = 78;
    public int JJTDICTIONARYPAIR = 79;
    public int JJTTUPLEDISPLAY = 80;
    public int JJTIFEXPR = 81;
    public int JJTIFBODY = 82;
    public int JJTWHILELOOPEXPR = 83;
    public int JJTLITERAL = 84;
    public int JJTINTLITERAL = 85;
    public int JJTDECIMALINTLITERAL = 86;
    public int JJTHEXINTLITERAL = 87;
    public int JJTOCTINTLITERAL = 88;
    public int JJTBINARYINTLITERAL = 89;
    public int JJTFLOATLITERAL = 90;
    public int JJTDECIMALFPLITERAL = 91;
    public int JJTHEXADECIMALFPLITERAL = 92;
    public int JJTBOOLLITERAL = 93;
    public int JJTCHARLITERAL = 94;
    public int JJTSTRINGLITERAL = 95;
    public int JJTUNDEFINEDLITERAL = 96;
    public int JJTMETHODINVOCATION = 97;
    public int JJTVOID = 98;
    public int JJTMETHODNAME = 99;
    public int JJTEXPRESSIONNAME = 100;
    public int JJTARGUMENTS = 101;
    public int JJTARGUMENT = 102;
    public int JJTFUNCTIONLITERAL = 103;
    public int JJTFUNCLITERALARG = 104;
    public int JJTIDENTIFIERTYPEBINDING = 105;
    public int JJTAMBIGUOUSNAME = 106;
    public int JJTSTATEMENT = 107;
    public int JJTFUNCALIAS = 108;
    public int JJTFUNCTIONNAME = 109;

    public String[] jjtNodeName = {
        "CompileUnit",
        "PackageDecl",
        "ModuleName",
        "ImportStmt",
        "SimpleImport",
        "AliasImport",
        "ImportAfter",
        "TypeName",
        "TypeDecl",
        "ClassDecl",
        "ClassModifier",
        "TypeParameters",
        "TypeParameter",
        "TypeBound",
        "ClassOrInterfaceType",
        "ClassType",
        "AdditionalBound",
        "SuperType",
        "Interfaces",
        "InterfaceType",
        "ClassBody",
        "ClassBodyDecl",
        "ClassCtorDecl",
        "CtorModifier",
        "FormalParameters",
        "FormalParameter",
        "LastFormalParamter",
        "VariableModifier",
        "CtorBody",
        "ExplicitCtorInvocation",
        "BlockStmts",
        "BlockStmt",
        "LocalValDecl",
        "VariableInitializer",
        "VariableType",
        "FieldDecl",
        "FieldModifier",
        "FieldInitializer",
        "FuncDecl",
        "FuncModifier",
        "ReturnType",
        "FuncBody",
        "AlgebraicDataTypeDecl",
        "AlgebraicDataTypeBody",
        "AlgebraicDataCtorBinding",
        "InterfaceDecl",
        "InterfaceModifier",
        "ExtendsInterfaces",
        "InterfaceBody",
        "InterfaceMember",
        "ConstantDecl",
        "ConstantModifier",
        "InterfaceMethodDecl",
        "TypeAliasDecl",
        "TypeAliasModifier",
        "EnumDecl",
        "EnumModifier",
        "EnumName",
        "EnumMembers",
        "Identifier",
        "Expression",
        "AssignmentExpr",
        "AssignmentOp",
        "LeftHandSide",
        "BoolOrExpr",
        "BoolAndExpr",
        "EqualityExpr",
        "RelationalExpr",
        "RangeExpr",
        "AdditiveExpr",
        "MultiplicativeExpr",
        "UnaryExpr",
        "UnaryExprNotPlusMinus",
        "CastExpr",
        "CheckExpr",
        "PostFixExpr",
        "Primary",
        "ListDisplay",
        "DictionaryDisplay",
        "DictionaryPair",
        "TupleDisplay",
        "IfExpr",
        "IfBody",
        "WhileLoopExpr",
        "Literal",
        "IntLiteral",
        "DecimalIntLiteral",
        "HexIntLiteral",
        "OctIntLiteral",
        "BinaryIntLiteral",
        "FloatLiteral",
        "DecimalFPLiteral",
        "HexadecimalFPLiteral",
        "BoolLiteral",
        "CharLiteral",
        "StringLiteral",
        "UndefinedLiteral",
        "MethodInvocation",
        "void",
        "MethodName",
        "ExpressionName",
        "Arguments",
        "Argument",
        "FunctionLiteral",
        "FuncLiteralArg",
        "IdentifierTypeBinding",
        "AmbiguousName",
        "Statement",
        "FuncAlias",
        "FunctionName",};
}
/* JavaCC - OriginalChecksum=f352f55b573bb930b5c509987ef01793 (do not edit this line) */
