/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package net.nokok.karaffe.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UndefinedLiteral = 63;
  /** RegularExpression Id. */
  int NullLiteral = 64;
  /** RegularExpression Id. */
  int BoolLiteral = 65;
  /** RegularExpression Id. */
  int DecimalNumeral = 66;
  /** RegularExpression Id. */
  int Digit = 67;
  /** RegularExpression Id. */
  int Zero = 68;
  /** RegularExpression Id. */
  int NonZero = 69;
  /** RegularExpression Id. */
  int HexNumeral = 70;
  /** RegularExpression Id. */
  int HexDigit = 71;
  /** RegularExpression Id. */
  int OctalIntLiteral = 72;
  /** RegularExpression Id. */
  int OctalDigit = 73;
  /** RegularExpression Id. */
  int BinaryNumeral = 74;
  /** RegularExpression Id. */
  int BinaryDigit = 75;
  /** RegularExpression Id. */
  int DecimalFPLiteral = 76;
  /** RegularExpression Id. */
  int Exp = 77;
  /** RegularExpression Id. */
  int HexadecimalFPLiteral = 78;
  /** RegularExpression Id. */
  int HexSignificand = 79;
  /** RegularExpression Id. */
  int BinaryExp = 80;
  /** RegularExpression Id. */
  int CharLiteral = 81;
  /** RegularExpression Id. */
  int StringLiteral = 82;
  /** RegularExpression Id. */
  int StringCharacter = 83;
  /** RegularExpression Id. */
  int StringEscapeSeq = 84;
  /** RegularExpression Id. */
  int UnicodeEscape = 85;
  /** RegularExpression Id. */
  int RawStringLiteral = 86;
  /** RegularExpression Id. */
  int EndOfLine = 107;
  /** RegularExpression Id. */
  int Identifier = 109;
  /** RegularExpression Id. */
  int IDHead = 110;
  /** RegularExpression Id. */
  int IDBody = 111;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int InComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"package\"",
    "\"import\"",
    "\"->\"",
    "\".\"",
    "\"*\"",
    "\"funcalias\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"type\"",
    "\"enum\"",
    "\"case\"",
    "\"interface\"",
    "\"typealias\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"<\"",
    "\"&\"",
    "\"func\"",
    "\"this\"",
    "\"def\"",
    "\"super\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"|>\"",
    "\"<|\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"..\"",
    "\".<\"",
    "\"+\"",
    "\"-\"",
    "\"+?\"",
    "\"-?\"",
    "\"/\"",
    "\"%\"",
    "\"*?\"",
    "\"/?\"",
    "\"%?\"",
    "\"!\"",
    "\"~>\"",
    "\"~>?\"",
    "\"::\"",
    "\"if\"",
    "\"else\"",
    "\"match\"",
    "\"=>\"",
    "\"while\"",
    "\"undefined\"",
    "\"null\"",
    "<BoolLiteral>",
    "<DecimalNumeral>",
    "<Digit>",
    "\"0\"",
    "<NonZero>",
    "<HexNumeral>",
    "<HexDigit>",
    "<OctalIntLiteral>",
    "<OctalDigit>",
    "<BinaryNumeral>",
    "<BinaryDigit>",
    "<DecimalFPLiteral>",
    "<Exp>",
    "<HexadecimalFPLiteral>",
    "<HexSignificand>",
    "<BinaryExp>",
    "<CharLiteral>",
    "<StringLiteral>",
    "<StringCharacter>",
    "<StringEscapeSeq>",
    "<UnicodeEscape>",
    "<RawStringLiteral>",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"abstract\"",
    "\"static\"",
    "\"final\"",
    "\"sealed\"",
    "\"var\"",
    "\"override\"",
    "\"auto\"",
    "\"self\"",
    "<token of kind 98>",
    "\"/*\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"/*\"",
    "<token of kind 106>",
    "<EndOfLine>",
    "\"*/\"",
    "<Identifier>",
    "<IDHead>",
    "<IDBody>",
  };

}
