/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package net.nokok.karaffe.parser;

public interface ParserTreeConstants {

    public int JJTCOMPILEUNIT = 0;
    public int JJTPACKAGEDECL = 1;
    public int JJTVOID = 2;
    public int JJTIMPORTSTMT = 3;
    public int JJTSIMPLEIMPORT = 4;
    public int JJTSTARIMPORT = 5;
    public int JJTALIASIMPORT = 6;
    public int JJTIMPORTAFTER = 7;
    public int JJTURLIMPORT = 8;
    public int JJTTYPENAME = 9;
    public int JJTSTATEMENT = 10;
    public int JJTFUNCALIAS = 11;
    public int JJTFUNCTIONNAME = 12;
    public int JJTCLASSDECL = 13;
    public int JJTCLASSMODIFIERS = 14;
    public int JJTTYPEPARAMETERS = 15;
    public int JJTTYPEPARAMETER = 16;
    public int JJTTYPEBOUND = 17;
    public int JJTCLASSORINTERFACETYPE = 18;
    public int JJTCLASSTYPE = 19;
    public int JJTADDITIONALBOUND = 20;
    public int JJTSUPERTYPE = 21;
    public int JJTINTERFACES = 22;
    public int JJTINTERFACETYPE = 23;
    public int JJTCLASSBODY = 24;
    public int JJTCLASSCTORDECL = 25;
    public int JJTCTORMODIFIERS = 26;
    public int JJTFORMALPARAMETERS = 27;
    public int JJTFORMALPARAMETER = 28;
    public int JJTLASTFORMALPARAMTER = 29;
    public int JJTVARIABLEMODIFIER = 30;
    public int JJTCTORBODY = 31;
    public int JJTEXPLICITCTORINVOCATION = 32;
    public int JJTBLOCKSTMTS = 33;
    public int JJTBLOCKSTMT = 34;
    public int JJTLOCALVALDECL = 35;
    public int JJTVARIABLEINITIALIZER = 36;
    public int JJTFIELDDECL = 37;
    public int JJTFIELDMODIFIERS = 38;
    public int JJTFIELDINITIALIZER = 39;
    public int JJTFUNCDECL = 40;
    public int JJTFUNCMODIFIERS = 41;
    public int JJTPARENFORMALPARAMS = 42;
    public int JJTRETURNTYPE = 43;
    public int JJTFUNCBODY = 44;
    public int JJTALGEBRAICDATATYPEDECL = 45;
    public int JJTALGEBRAICDATATYPEBODY = 46;
    public int JJTALGEBRAICDATACTORBINDING = 47;
    public int JJTINTERFACEDECL = 48;
    public int JJTINTERFACEMODIFIER = 49;
    public int JJTEXTENDSINTERFACES = 50;
    public int JJTINTERFACEBODY = 51;
    public int JJTINTERFACEMEMBER = 52;
    public int JJTCONSTANTDECL = 53;
    public int JJTINTERFACEMETHODDECL = 54;
    public int JJTTYPEALIASDECL = 55;
    public int JJTTYPEALIASMODIFIER = 56;
    public int JJTENUMDECL = 57;
    public int JJTENUMMODIFIER = 58;
    public int JJTENUMNAME = 59;
    public int JJTENUMMEMBERS = 60;
    public int JJTEXPRESSION = 61;
    public int JJTASSIGNMENTEXPR = 62;
    public int JJTASSIGNMENTOP = 63;
    public int JJTLEFTHANDSIDE = 64;
    public int JJTBOOLOR = 65;
    public int JJTEXPRNODE = 66;
    public int JJTBOOLAND = 67;
    public int JJTEQUALTO = 68;
    public int JJTNOTEQUALTO = 69;
    public int JJTLESSTHAN = 70;
    public int JJTGREATERTHAN = 71;
    public int JJTLESSTHANEQTO = 72;
    public int JJTGREATERTHANEQTO = 73;
    public int JJTCLOSEDRANGE = 74;
    public int JJTHALFOPENRANGE = 75;
    public int JJTADD = 76;
    public int JJTSUB = 77;
    public int JJTSAFEADD = 78;
    public int JJTSAFESUB = 79;
    public int JJTMUL = 80;
    public int JJTDIV = 81;
    public int JJTREM = 82;
    public int JJTSAFEMUL = 83;
    public int JJTSAFEDIV = 84;
    public int JJTSAFEREM = 85;
    public int JJTUADD = 86;
    public int JJTUSUB = 87;
    public int JJTUBANG = 88;
    public int JJTLISTDISPLAY = 89;
    public int JJTDICTIONARYDISPLAY = 90;
    public int JJTDICTIONARYPAIR = 91;
    public int JJTTUPLEDISPLAY = 92;
    public int JJTIFEXPR = 93;
    public int JJTIFBODY = 94;
    public int JJTSWITCHEXPR = 95;
    public int JJTSWITCHCASE = 96;
    public int JJTSWITCHCOND = 97;
    public int JJTCASEBODY = 98;
    public int JJTWHILELOOPEXPR = 99;
    public int JJTWHILEBODY = 100;
    public int JJTMETHODINVOCATION = 101;
    public int JJTMETHODNAME = 102;
    public int JJTEXPRESSIONNAME = 103;
    public int JJTARGUMENTS = 104;
    public int JJTARGUMENT = 105;
    public int JJTFUNCTIONLITERAL = 106;
    public int JJTFUNCLITERALARG = 107;
    public int JJTIDENTIFIERTYPEBINDING = 108;
    public int JJTAMBIGUOUSNAME = 109;
    public int JJTDECIMALINTLITERAL = 110;
    public int JJTHEXINTLITERAL = 111;
    public int JJTOCTINTLITERAL = 112;
    public int JJTBINARYINTLITERAL = 113;
    public int JJTFLOATLITERAL = 114;
    public int JJTDECIMALFPLITERAL = 115;
    public int JJTHEXADECIMALFPLITERAL = 116;
    public int JJTBOOLLITERAL = 117;
    public int JJTCHARLITERAL = 118;
    public int JJTSTRINGLITERAL = 119;
    public int JJTUNDEFINEDLITERAL = 120;
    public int JJTNULLLITERAL = 121;
    public int JJTPUBLICMODIFIER = 122;
    public int JJTPROTECTEDMODIFIER = 123;
    public int JJTPRIVATEMODIFIER = 124;
    public int JJTABSTRACTMODIFIER = 125;
    public int JJTSTATICMODIFIER = 126;
    public int JJTFINALMODIFIER = 127;
    public int JJTSEALEDMODIFIER = 128;
    public int JJTVARMODIFIER = 129;
    public int JJTOVERRIDEMODIFIER = 130;
    public int JJTAUTOMODIFIER = 131;
    public int JJTIDENTIFIER = 132;

    public String[] jjtNodeName = {
        "CompileUnit",
        "PackageDecl",
        "void",
        "ImportStmt",
        "SimpleImport",
        "StarImport",
        "AliasImport",
        "ImportAfter",
        "URLImport",
        "TypeName",
        "Statement",
        "FuncAlias",
        "FunctionName",
        "ClassDecl",
        "ClassModifiers",
        "TypeParameters",
        "TypeParameter",
        "TypeBound",
        "ClassOrInterfaceType",
        "ClassType",
        "AdditionalBound",
        "SuperType",
        "Interfaces",
        "InterfaceType",
        "ClassBody",
        "ClassCtorDecl",
        "CtorModifiers",
        "FormalParameters",
        "FormalParameter",
        "LastFormalParamter",
        "VariableModifier",
        "CtorBody",
        "ExplicitCtorInvocation",
        "BlockStmts",
        "BlockStmt",
        "LocalValDecl",
        "VariableInitializer",
        "FieldDecl",
        "FieldModifiers",
        "FieldInitializer",
        "FuncDecl",
        "FuncModifiers",
        "ParenFormalParams",
        "ReturnType",
        "FuncBody",
        "AlgebraicDataTypeDecl",
        "AlgebraicDataTypeBody",
        "AlgebraicDataCtorBinding",
        "InterfaceDecl",
        "InterfaceModifier",
        "ExtendsInterfaces",
        "InterfaceBody",
        "InterfaceMember",
        "ConstantDecl",
        "InterfaceMethodDecl",
        "TypeAliasDecl",
        "TypeAliasModifier",
        "EnumDecl",
        "EnumModifier",
        "EnumName",
        "EnumMembers",
        "Expression",
        "AssignmentExpr",
        "AssignmentOp",
        "LeftHandSide",
        "BoolOr",
        "ExprNode",
        "BoolAnd",
        "EqualTo",
        "NotEqualTo",
        "LessThan",
        "GreaterThan",
        "LessThanEqTo",
        "GreaterThanEqTo",
        "ClosedRange",
        "HalfOpenRange",
        "Add",
        "Sub",
        "SafeAdd",
        "SafeSub",
        "Mul",
        "Div",
        "Rem",
        "SafeMul",
        "SafeDiv",
        "SafeRem",
        "UAdd",
        "USub",
        "UBang",
        "ListDisplay",
        "DictionaryDisplay",
        "DictionaryPair",
        "TupleDisplay",
        "IfExpr",
        "IfBody",
        "SwitchExpr",
        "SwitchCase",
        "SwitchCond",
        "CaseBody",
        "WhileLoopExpr",
        "WhileBody",
        "MethodInvocation",
        "MethodName",
        "ExpressionName",
        "Arguments",
        "Argument",
        "FunctionLiteral",
        "FuncLiteralArg",
        "IdentifierTypeBinding",
        "AmbiguousName",
        "DecimalIntLiteral",
        "HexIntLiteral",
        "OctIntLiteral",
        "BinaryIntLiteral",
        "FloatLiteral",
        "DecimalFPLiteral",
        "HexadecimalFPLiteral",
        "BoolLiteral",
        "CharLiteral",
        "StringLiteral",
        "UndefinedLiteral",
        "NullLiteral",
        "PublicModifier",
        "ProtectedModifier",
        "PrivateModifier",
        "AbstractModifier",
        "StaticModifier",
        "FinalModifier",
        "SealedModifier",
        "VarModifier",
        "OverrideModifier",
        "AutoModifier",
        "Identifier",};
}
/* JavaCC - OriginalChecksum=8fc1cd6d851e0ef7a4ff3a53bc161929 (do not edit this line) */
