/* Generated By:JJTree: Do not edit this line. ASTAlgebraicDataTypeDecl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package karaffe.compiler.phase.parser;

public
class ASTAlgebraicDataTypeDecl extends SimpleNode {
  public ASTAlgebraicDataTypeDecl(int id) {
    super(id);
  }

  public ASTAlgebraicDataTypeDecl(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(ParserVisitor visitor, Object data) throws karaffe.compiler.ParserException {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e136b0ddb361f06f8bfbe27bcf021a34 (do not edit this line) */
