/* Generated By:JJTree: Do not edit this line. ASTFuncDecl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package karaffe.compiler.phase.parser;

public
class ASTFuncDecl extends SimpleNode {
  public ASTFuncDecl(int id) {
    super(id);
  }

  public ASTFuncDecl(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(ParserVisitor visitor, Object data) throws karaffe.compiler.ParserException {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9980c4163631c8b9f9d0a6e59679fa6c (do not edit this line) */
