/* Generated By:JJTree: Do not edit this line. ASTOr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package karaffe.compiler.phase.parser;

public
class ASTOr extends SimpleNode {
  public ASTOr(int id) {
    super(id);
  }

  public ASTOr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(ParserVisitor visitor, Object data) throws karaffe.compiler.ParserException {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=28e25dafb07c783d26b57c2888245d95 (do not edit this line) */
