/* Generated By:JJTree: Do not edit this line. ASTSwitchGuard.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package karaffe.compiler.phase.parser;

public
class ASTSwitchGuard extends SimpleNode {
  public ASTSwitchGuard(int id) {
    super(id);
  }

  public ASTSwitchGuard(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(ParserVisitor visitor, Object data) throws karaffe.compiler.ParserException {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ba3bc89092bce1cbffb2557277205738 (do not edit this line) */
