/* Generated By:JJTree: Do not edit this line. ASTVariableInitializer.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package karaffe.compiler.phase.parser;

public
class ASTVariableInitializer extends SimpleNode {
  public ASTVariableInitializer(int id) {
    super(id);
  }

  public ASTVariableInitializer(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(ParserVisitor visitor, Object data) throws karaffe.compiler.ParserException {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0df4a78d938b72e97c5ce67a89584dc (do not edit this line) */
