// Generated from Karaffe.g4 by ANTLR 4.7.1
package org.karaffe.compiler.frontend.karaffe.antlrautogenerated;
import org.antlr.v4.runtime.tree.ParseTreeVisitor;

/**
 * This interface defines a complete generic visitor for a parse tree produced
 * by {@link KaraffeParser}.
 *
 * @param <T> The return type of the visit operation. Use {@link Void} for
 * operations with no return type.
 */
public interface KaraffeVisitor<T> extends ParseTreeVisitor<T> {
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#compilationUnit}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCompilationUnit(KaraffeParser.CompilationUnitContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#topLevelStatement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTopLevelStatement(KaraffeParser.TopLevelStatementContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#classDef}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitClassDef(KaraffeParser.ClassDefContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#simpleClassDef}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSimpleClassDef(KaraffeParser.SimpleClassDefContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#classDefBody}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitClassDefBody(KaraffeParser.ClassDefBodyContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#classDefMember}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitClassDefMember(KaraffeParser.ClassDefMemberContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#mainMethodDef}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitMainMethodDef(KaraffeParser.MainMethodDefContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitStatement(KaraffeParser.StatementContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#expr}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitExpr(KaraffeParser.ExprContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#additiveExpr}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAdditiveExpr(KaraffeParser.AdditiveExprContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#multiplicativeExpr}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitMultiplicativeExpr(KaraffeParser.MultiplicativeExprContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#primary}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitPrimary(KaraffeParser.PrimaryContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#argumentList}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitArgumentList(KaraffeParser.ArgumentListContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#literal}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitLiteral(KaraffeParser.LiteralContext ctx);
	/**
	 * Visit a parse tree produced by {@link KaraffeParser#intLiteral}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitIntLiteral(KaraffeParser.IntLiteralContext ctx);
}